# Generated by Django 5.0.3 on 2024-04-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_app', '0002_department_course_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='Key_pts',
        ),
        migrations.AddField(
            model_name='topic',
            name='key_points',
            field=models.CharField(default='Default key points', max_length=1000),
        ),
    ]
