# Generated by Django 5.0.3 on 2024-04-09 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_app', '0004_alter_topic_key_points_question_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='text',
            new_name='question_text',
        ),
    ]
