# Generated by Django 5.0.3 on 2024-04-09 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_app', '0005_rename_text_question_question_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='text',
        ),
    ]
