# Generated by Django 5.0.3 on 2024-04-10 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_app', '0006_rename_question_text_question_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
