# Generated by Django 5.0.3 on 2024-04-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_app', '0008_answer_created_at_answer_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_num',
        ),
        migrations.AddField(
            model_name='department',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='0000', max_length=128),
        ),
    ]
